In [1]:
#operations
import numpy as np

In [2]:
#scalar operations
a = np.array([10,30,50])
print(f"sum: {a + 5}")
print(f"sub: {a - 5}")
print(f"mul: {a * 5}")
print(f"div: {a / 3}")
print(f"quotient: {a // 3}")
print(f"rem: {a % 3}")
print(f"power: {a ** 3}")

sum: [15 35 55]
sub: [ 5 25 45]
mul: [ 50 150 250]
div: [ 3.33333333 10.         16.66666667]
quotient: [ 3 10 16]
rem: [1 0 2]
power: [  1000  27000 125000]


In [3]:
#vector operation
b = np.array([[1.4,2.3,3.6,4.6],
             [5.6,6.2,7.8,8.5]])
print(np.sqrt(b))
print(np.round(b))
print(np.ceil(b))
print(np.floor(b))

[[1.18321596 1.51657509 1.8973666  2.14476106]
 [2.36643191 2.48997992 2.79284801 2.91547595]]
[[1. 2. 4. 5.]
 [6. 6. 8. 8.]]
[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [4]:
#element wise
c = np.array([1,3,5])
d = np.array([7,9,11])
print(f"sum: {c + d}")
print(f"sub: {c - d}")
print(f"mul: {c * d}")
print(f"div: {c / d}")
print(f"quotient: {c // d}")
print(f"rem: {c % d}")
print(f"power: {c ** d}")
print(np.dot(c,d))

sum: [ 8 12 16]
sub: [-6 -6 -6]
mul: [ 7 27 55]
div: [0.14285714 0.33333333 0.45454545]
quotient: [0 0 0]
rem: [1 3 5]
power: [       1    19683 48828125]
89


In [5]:
#broadcasting
d = np.array([[1,2,3]])
e = np.array([[1],[2],[3],[4]])
print(np.shape(d))
print(np.shape(e))
print(d * e)
print(np.shape(d * e))

(1, 3)
(4, 1)
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]
(4, 3)


In [6]:
#aggregation
f = np.array([[[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]]])
print(np.sum(f))
print(np.mean(f))
print(np.min(f))
print(np.max(f))
print(np.std(f))
print(np.var(f))
print(np.argmin(f))
print(np.argmax(f))
print(np.sum(f,axis = 1))
print(np.sum(f,axis = 0))
print(np.sum(f,axis=2))


120
8.0
1
15
4.320493798938574
18.666666666666668
0
14
[[18 21 24 27 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[15 40 65]]


In [7]:
# or -> | and -> &
g = np.array([[20,21,16,15,24],[32,45,53,64,80]])
teen = g[g <= 18]
adult = g[ (g >= 18) & (g <= 60) ]
old = g[g >= 60]
x = np.where(((g >= 18) & (g <= 60)),g,0)
print(f"{teen}\n{adult}\n{old}\n{x}")

[16 15]
[20 21 24 32 45 53]
[64 80]
[[20 21  0  0 24]
 [32 45 53  0  0]]


In [8]:
# random generator
rng = np.random.default_rng()
guess = rng.integers(1,100)
arr = rng.integers(1,101, size = (2,2))
print(guess,arr)
q = np.arange(1,10,2)
po = np.linspace(0,1,5)
print(q)
print(po)

61 [[12 18]
 [35 90]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
float = np.random.uniform(1,100)
aj = np.random.uniform(-1,1,size=(2,2))
print(float,aj)

45.77358389918818 [[-0.3766145  -0.23629113]
 [ 0.53904735 -0.54771289]]


In [10]:
jj  = np.array([1,3,5,7,9])
print(rng.shuffle(jj))
print(jj)
print(rng.choice(jj))
print(rng.choice(jj,size=(2,3)))

None
[3 5 9 7 1]
7
[[9 5 9]
 [5 1 1]]
