In [1]:
#multidimenisonal array, indexing,slicing
import numpy as np

In [4]:
A = np.array([1,2,3])

In [5]:
print(A)

[1 2 3]


In [6]:
np.version.version

'2.3.2'

In [11]:
print(type(A))
print(A.ndim)
print(f"shape:{A.shape}")

<class 'numpy.ndarray'>
1
shape:(3,)


In [12]:
c = A*2
print(c)
d = np.array([A,A])
print(d.ndim)
print(d.shape)
b= np.array(1)
print(b.ndim)
print(f"shape:{b.shape}")



[2 4 6]
2
(2, 3)
0
shape:()


In [13]:
e = np.array([[['A','B'],['A','B'],['A','B']],[['A','B'],['A','B'],['A','B']],[['A','B'],['A','B'],['A','B']]])
print(e)
print(e.ndim)
print(e.shape)

[[['A' 'B']
  ['A' 'B']
  ['A' 'B']]

 [['A' 'B']
  ['A' 'B']
  ['A' 'B']]

 [['A' 'B']
  ['A' 'B']
  ['A' 'B']]]
3
(3, 3, 2)


In [14]:
f = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
              [['J','K','L'],['M','N','O'],['P','Q','R']],
              [['S','T','U'],['V','W','X'],['Y','Z','!']]])
print(f.ndim)
print (f[1,1,1] == f[1][1][1])

3
True


In [15]:
#string concatenation
word = f[2,1,0] + f[0,2,2] + f[2,0,0] + f[0,2,1] + f[1,1,1] + f[2,0,2] + f[2,2,2]
print(word.title())

Vishnu!


In [16]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])


In [17]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
print(a[0:2])
print(a[0::2])
print(a[::-1])


[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [19]:
print(a[:,0:])
print(a[:,0:4:2])
print(a[:,::-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [20]:
print(a[1:3,1:3])

[[ 6  7]
 [10 11]]
